const browserBase = {
  domain: "browser",
  timeoutMs: 300_000,
  batchBuild: false,
  batchSize: null,
};

const codeBase = {
  domain: "code",
  timeoutMs: 600_000,
  batchBuild: false,
  batchSize: null,
  skillIds: [],
};

const pptBase = {
  domain: "ppt",
  timeoutMs: 1_800_000,
  skillIds: ["polaris-deck-studio"],
};

export const SCENARIOS = [
  {
    ...browserBase,
    id: "browser-catalog-first-page",
    name: "动态目录首屏",
    skillIds: ["cloak-browser"],
    promptTemplate: "必须使用 Polaris 的 CloakBrowser 打开 {{fixtureBaseUrl}}/catalog，等待动态列表出现，只读取第一页。返回 AS-101、Aster、1299 和页面指示器；写出实际访问 URL。仅访问这个本地夹具。",
    expectedTokens: ["AS-101", "Aster", "1299", "PAGE-1-OF-3"],
  },
  {
    ...browserBase,
    id: "browser-multipage-local",
    name: "多页自主导航",
    skillIds: ["cloak-browser", "browser-use"],
    promptTemplate: "使用 Polaris 浏览器智能体在 {{fixtureBaseUrl}}/catalog 自主点击翻完 3 页，找出价格最高的产品，再打开它的详情页。最终必须给出 CY-303、Cygnus、1599、C-GAMMA-9 和访问过的 URL。仅操作本地夹具。",
    expectedTokens: ["CY-303", "Cygnus", "1599", "C-GAMMA-9"],
  },
  {
    ...browserBase,
    id: "browser-dynamic-aggregate",
    name: "动态数据聚合",
    skillIds: ["cloak-browser", "browser-use"],
    promptTemplate: "使用 Polaris 的浏览器能力读取 {{fixtureBaseUrl}}/catalog 全部三页。只统计 category=workstation 的产品，给出数量 2 和价格合计 2798，并列出两个产品 ID。不得改用外部网站。",
    expectedTokens: ["2", "2798", "CY-303", "EQ-505"],
  },
  {
    ...browserBase,
    id: "browser-download-csv",
    name: "浏览器下载并核对 CSV",
    skillIds: ["cloak-browser"],
    promptTemplate: "用 Polaris 的 CloakBrowser 访问并下载 {{fixtureBaseUrl}}/report.csv，读取 6 行数据并计算 units 合计。答案必须包含 6、94、report.csv，并说明文件来自本地夹具 URL。",
    expectedTokens: ["6", "94", "report.csv"],
  },
  {
    ...browserBase,
    id: "browser-slow-response",
    name: "慢页面等待",
    skillIds: ["cloak-browser"],
    promptTemplate: "用 Polaris 的 CloakBrowser 打开 {{fixtureBaseUrl}}/slow?ms=1200，耐心等待页面完成，不要提前猜答案。返回页面中的完整标记 SLOW-READY-1200 和实际 URL。",
    expectedTokens: ["SLOW-READY-1200"],
  },
  {
    ...browserBase,
    id: "browser-local-form",
    name: "本地无副作用表单",
    skillIds: ["cloak-browser", "browser-use"],
    promptTemplate: "使用 Polaris 浏览器智能体打开 {{fixtureBaseUrl}}/form，在本地测试表单填入 STRESS-ONLY 并提交校验。返回确认标记 FORM-ACCEPTED-STRESS-ONLY；不要访问本地夹具以外的地址。",
    expectedTokens: ["FORM-ACCEPTED-STRESS-ONLY"],
  },
  {
    ...browserBase,
    id: "browser-cross-source-local",
    name: "站内跨来源核验",
    skillIds: ["cloak-browser", "browser-use"],
    promptTemplate: "通过 Polaris 浏览器先在 {{fixtureBaseUrl}}/catalog 找最高价产品，再用 {{fixtureBaseUrl}}/report.csv 核验同一 ID 的 units。答案必须包含 CY-303、1599、27 和两个来源 URL。",
    expectedTokens: ["CY-303", "1599", "27", "report.csv"],
  },
  {
    ...browserBase,
    id: "browser-layout-change",
    name: "页面结构变化",
    skillIds: ["cloak-browser"],
    promptTemplate: "使用 Polaris 的 CloakBrowser 打开 {{fixtureBaseUrl}}/alternate。页面结构与目录不同，请读取嵌套卡片并返回 LAYOUT-V2-ORION 与 data-layout 的值 cards-v2。",
    expectedTokens: ["LAYOUT-V2-ORION", "cards-v2"],
  },
  {
    ...codeBase,
    id: "code-discount-percentage",
    name: "折扣百分比缺陷",
    fixtureCase: "case-files/discount-percentage.case.mjs",
    promptTemplate: "你正在 Polaris 绑定的隔离代码夹具 {{workDir}} 中工作。只修复折扣百分比计算，使 `npm test -- case-files/discount-percentage.case.mjs` 通过；先读实现和测试，最小改动，必须真实运行该命令。不要修改夹具目录之外的文件。",
  },
  {
    ...codeBase,
    id: "code-invalid-quantity",
    name: "数量校验边界",
    fixtureCase: "case-files/invalid-quantity.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中修复订单行数量校验：0、负数和非整数都必须拒绝。以 `npm test -- case-files/invalid-quantity.case.mjs` 为完成条件并真实运行；不要改目录外文件。",
  },
  {
    ...codeBase,
    id: "code-immutable-sort",
    name: "稳定排序与不可变输入",
    fixtureCase: "case-files/immutable-sort.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中修复订单排序，使时间相同时保持原顺序且不修改输入数组。真实运行 `npm test -- case-files/immutable-sort.case.mjs`，只改完成此任务所需代码。",
  },
  {
    ...codeBase,
    id: "code-regional-tax",
    name: "区域税率功能",
    fixtureCase: "case-files/regional-tax.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中实现区域税率：JP=10%、SG=9%、未知区域=0，并按整数分币四舍五入。运行 `npm test -- case-files/regional-tax.case.mjs` 验证。",
  },
  {
    ...codeBase,
    id: "code-next-order-id",
    name: "非连续订单号",
    fixtureCase: "case-files/next-order-id.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中修复 nextOrderId：已有编号不连续时也必须生成最大编号加一。真实运行 `npm test -- case-files/next-order-id.case.mjs`。",
  },
  {
    ...codeBase,
    id: "code-immutable-add",
    name: "不可变新增订单",
    fixtureCase: "case-files/immutable-add.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中修复 addOrder，使它返回新数组且不改变调用方原数组。以 `npm test -- case-files/immutable-add.case.mjs` 通过为完成条件。",
  },
  {
    ...codeBase,
    id: "code-normalized-grouping",
    name: "客户名归一分组",
    fixtureCase: "case-files/normalized-grouping.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中修复客户分组：忽略姓名首尾空格和大小写，同时不丢订单。运行 `npm test -- case-files/normalized-grouping.case.mjs`。",
  },
  {
    ...codeBase,
    id: "code-quantity-summary",
    name: "订单金额汇总",
    fixtureCase: "case-files/quantity-summary.case.mjs",
    promptTemplate: "在隔离夹具 {{workDir}} 中修复订单汇总总额，必须计入每行 quantity 并返回订单数。真实运行 `npm test -- case-files/quantity-summary.case.mjs`。",
  },
  {
    ...pptBase,
    id: "ppt-12-executive",
    name: "12 页经营简报",
    expectedSlides: 12,
    batchBuild: false,
    batchSize: 8,
    promptTemplate: "使用 Polaris 演示工坊在 {{workDir}} 制作恰好 12 页中文经营简报，标题为《北辰零售经营简报》，含封面、目录、指标、趋势、问题、行动和结尾。必须生成 polaris.slides.json、HTML 源稿和可打开 PPTX，全部放在该目录。",
    requiredText: ["北辰零售经营简报", "行动"],
  },
  {
    ...pptBase,
    id: "ppt-30-data-story",
    name: "30 页数据故事",
    expectedSlides: 30,
    batchBuild: true,
    batchSize: 6,
    promptTemplate: "使用 Polaris 演示工坊在 {{workDir}} 分批制作恰好 30 页《星港增长数据故事》。用明确章节、数据图表占位和结论页；创建 polaris.build.json 并逐批回写状态，最终交付 polaris.slides.json、HTML 和 PPTX。",
    requiredText: ["星港增长数据故事", "增长"],
  },
  {
    ...pptBase,
    id: "ppt-60-long",
    name: "60 页长演示",
    expectedSlides: 60,
    batchBuild: true,
    batchSize: 4,
    promptTemplate: "使用 Polaris 演示工坊在 {{workDir}} 分批制作恰好 60 页《远航 2030 战略蓝图》。必须先写 polaris.build.json，再每批只完成 4 页并回写状态，直至全部 done；最终生成 polaris.slides.json、HTML 源稿和 PPTX。",
    requiredText: ["远航 2030 战略蓝图", "战略"],
  },
  {
    ...pptBase,
    id: "ppt-12-bilingual",
    name: "12 页双语产品发布",
    expectedSlides: 12,
    batchBuild: false,
    batchSize: 8,
    promptTemplate: "使用 Polaris 演示工坊在 {{workDir}} 制作恰好 12 页中英双语产品发布演示《Aurora Launch / 极光发布》，每页标题双语，交付 polaris.slides.json、HTML 与 PPTX。",
    requiredText: ["Aurora Launch", "极光发布"],
  },
  {
    ...pptBase,
    id: "ppt-30-training",
    name: "30 页培训课件",
    expectedSlides: 30,
    batchBuild: true,
    batchSize: 6,
    promptTemplate: "使用 Polaris 演示工坊在 {{workDir}} 分批制作恰好 30 页《Agent 工具使用安全培训》，包含学习目标、示例、练习、检查表和总结；交付完成态 build 清单、polaris.slides.json、HTML 与 PPTX。",
    requiredText: ["Agent 工具使用安全培训", "检查表"],
  },
  {
    ...pptBase,
    id: "ppt-60-recovery",
    name: "60 页续跑课件",
    expectedSlides: 60,
    batchBuild: true,
    batchSize: 4,
    promptTemplate: "在 {{workDir}} 使用 Polaris 演示工坊构建恰好 60 页《复杂项目交付手册》。严格按 polaris.build.json 分批，每批最多 4 页，允许后续轮次从 pending 继续；最终交付 HTML、polaris.slides.json 和 PPTX。",
    requiredText: ["复杂项目交付手册", "交付"],
  },
];

export function scenarioPrompt(scenario, { fixtureBaseUrl, workDir }) {
  return scenario.promptTemplate
    .replaceAll("{{fixtureBaseUrl}}", fixtureBaseUrl)
    .replaceAll("{{workDir}}", workDir);
}
